version: '3'
services:
  app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
      - ./entrypoint.sh:/entrypoint.sh
    command: sh /entrypoint.sh
  db:
    container_name: db
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: shopping_cart
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
